FROM ghcr.io/puppeteer/puppeteer:17.0.0

# Dossier de travail dans le container
WORKDIR /home/pptruser/src

# On copie tout le contenu du dossier probe-action dans l'image
COPY . .

# Commande par défaut : exécuter notre script Node
CMD ["node", "/home/pptruser/src/probe.js"]